### ISSUE TITLE
Meta model for `criticReview` in `TouristTrip` does not seem to be coherent with concrete example

### ISSUE THREAD

**Issue by isalvadori** [smart-data-models/dataModel.TourismDestinations#6]
Hi, 
looking at the meta model for `TouristTrip` (https://github.com/smart-data-models/dataModel.TourismDestinations/blob/master/TouristTrip/model.yaml), the `criticReview` attribute is defined as:

``` 
criticReview:
      description: "Review written or published by a source that is recognized for its reviewing activities. Each items have the format based on the  [Internationalization (i18N) - W3C recommendation for multilanguage](https://www.w3.org/TR/json-ld/#string-internationalization) integrating all items in a single property (ex number 71). Each item is represented by a string with 'Language Value' : 'Article Value'"
      properties:
        language:
          type: string
        reviews:
          items:
            article:
              type: string
            origin:
              type: string
            ratingValue:
              type: number
            starRating:
              type: number
          type: array
      type: object
      x-ngsi:
        type: Property
```

The description does not seem to match the listed `properties`. I mean, if I had to build a concrete example looking at this meta model, I would write something like:

```
"criticReview": {
   "language": "fr",
   "reviews": [{
       "article": "Some article",
       "origin": "Some origin",
       "ratingValue": 3.5,
       "starRating": 7
  }, 
  {
       "article": "Some other article",
       "origin": "Some other origin",
       "ratingValue": 6,
       "starRating": 9
  }]
}
```

while, if I look at the example you provided I can see something like:

```
"criticReview": {
    "fr": {
      "value": {
        "article": "Beau palais baroque qui contient des instruments de musique vari\u00e9s dont une harpe-piano \u00e9tonnante, et des portraits tr\u00e8s beaux. A voir, surtout pour l'escalier et la d\u00e9coration des salles.",
        "origine": "Office du tourisme Nice",
        "ratingValue": 9,
        "starRating": 5
      }
    },
    "en": {
      "value": {
        "article": "Beautiful baroque palace which contains various gastronomieal instruments including an astonishing harp-piano, and very beautiful portraits. To see, especially for the staircase and the decoration of the rooms.",
        "origine": "Trip Advisor",
        "ratingValue": 8,
        "starRating": 4
      }
    }
  }
```

which is indeed in line with the description of that attribute, but the meta model itself does not seem to be.
Or am I missing something?

Thanks!

**Comment by albertoabellagarcia** [comment]
you are right. 

fixed.

**Comment by isalvadori** [comment]
Hi, 
thank you for your prompt response. I still have some doubts though, concerning this topic.
You now fixed the example.json to match the model, but then they both do not match the description. So I am wondering which is the correct one, the model/example or the description?
According to the description:

```
Review written or published by a source that is recognized for its reviewing activities. 
Each items have the format based on the  [Internationalization (i18N) - W3C recommendation for multilanguage](https://www.w3.org/TR/json-ld/#string-internationalization) 
integrating all items in a single property (ex number 71). 
Each item is represented by a string with 'Language Value' : 'Article Value
```
So, looking at the link I would expect the `criticReview` to be an array of *language maps*. And, looking at their spec:
```
language map
    An [language map](https://www.w3.org/TR/json-ld/#dfn-language-map) is a 
[map](https://infra.spec.whatwg.org/#ordered-map) value of a 
[term](https://www.w3.org/TR/json-ld/#dfn-term) defined with 
@container set to @language, whose keys must be
[strings](https://infra.spec.whatwg.org/#javascript-string) representing [[BCP47](https://www.w3.org/TR/json-ld/#bib-bcp47)] language codes and the values must be any of the following types: 
[null](https://infra.spec.whatwg.org/#nulls), 
[string](https://infra.spec.whatwg.org/#javascript-string),
or an [array](https://infra.spec.whatwg.org/#list) of zero or more of the above possibilities. 
See the [Language Maps](https://www.w3.org/TR/json-ld/#language-maps) 
section of JSON-LD 1.1 for a normative description.
```
so, if this were the case for the `crititcReview` model, I wouldn't expect a complex object as value (such as the one we have with `article`, `origin` etc.).

On the other hand, if the model/example were the correct ones and the description should then be updated accordingly, I think it should also be changed the `type` of `criticReview` from `object` to `array`, where the items are then the objects described by:

```
properties:
        language:
          type: string
        reviews:
          items:
            article:
              type: string
            origin:
              type: string
            ratingValue:
              type: number
            starRating:
              type: number
          type: array
```

Thanks!
